const SYNC_STATUS_TURN_OFF = 'off'
const SYNC_STATUS_TURN_ON = 'on'
const DEFAULT_SYNC_STATUS = SYNC_STATUS_TURN_ON

const TIKTOK_INDEX_NAME = 'prod_tiktok'

module.exports = {
  SYNC_STATUS_TURN_ON,
  SYNC_STATUS_TURN_OFF,
  DEFAULT_SYNC_STATUS,
  TIKTOK_INDEX_NAME
};